### ISSUE TITLE
No API call for odds/parlay

### ISSUE THREAD

**Issue by peterkingsbury** [Kalagan/pinnacle-sports#1]
According to the [doc](http://www.pinnaclesports.com/en/api/manual#GetOdds), there are 2 types of odds requests, to /odds/ and to /odds/parlay/ (both use the same parameters). However pinnacle-sports NPM module only supplies /odds/ API call.

Adding the following to operations would solve this shortcoming:

```
{
    name: 'get_odds_parlay',
    endpoint: 'odds/parlay'
},
```

**Comment by JulienSansot** [comment]
I added it.
It's called **get_parlay_odds** . To be consistent with **place_parlay_bet** and **get_parlay_line**.
Thanks for filling this issue. I forgot about parlay odds.
