### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by sbefort** [Kalagan/pinnacle-sports#4]
I'm trying the example with my username and password and it just returns the pinnacle homepage HTML.  There is no XML or JSON response.

**Comment by JulienSansot** [comment]
I'll try to see what's wrong later today.

**Comment by sbefort** [comment]
Apparently if you call the Pinnacle API from an IP address in the United States, you are blocked.

**Comment by JulienSansot** [comment]
I thought only operations like "place bet" were blocked in that case.
Did you create your account from another country?

**Comment by sbefort** [comment]
If you read the version notes for 2/10/2014, it says, "Please note that in order to access Pinnacle Sports API the account must be funded."  It is not possible to fund the account with a U.S. address.  I do have a funded account from a different country, but I was trying to access the API from a U.S.-based server.  When I switched my server data center to another country, everything worked fine.
